spring:
  application:
    name: med-hub-api

  datasource:
    url: jdbc:mysql://localhost:3306/medhub_api?useSSL=false&serverTimezone=UTC
    username: root
    password: Diogenes@18124803
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true